---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-artistca
  labels:
    run: blockchain-artistca
spec:
  type: NodePort
  selector:
    name: artistca
  ports:
  - protocol: TCP
    nodePort: 30054
    targetPort: 7054
    port: 30054
    name: grpc
---

apiVersion: v1
kind: Service
metadata:
  name: blockchain-ordererflorence
  labels:
    run: blockchain-ordererflorence
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    nodePort: 31310
    targetPort: 31310
    port: 31310
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ordererparis
  labels:
    run: blockchain-ordererparis
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    nodePort: 31410
    targetPort: 31410
    port: 31410
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-artistflorence
  labels:
    run: blockchain-artistflorence
spec:
  type: NodePort
  selector:
    name: artistflorence
  ports:
  - protocol: TCP
    nodePort: 30110
    targetPort: 30110
    port: 30110
    name: grpc
  - protocol: TCP
    nodePort: 30111
    targetPort: 30111
    port: 30111
    name: events
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-artistparis
  labels:
    run: blockchain-artistparis
spec:
  type: NodePort
  selector:
    name: artistparis
  ports:
  - protocol: TCP
    nodePort: 30210
    targetPort: 30210
    port: 30210
    name: grpc
  - protocol: TCP
    nodePort: 30211
    targetPort: 30211
    port: 30211
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-brokerflorence
  labels:
    run: blockchain-brokerflorence
spec:
  type: NodePort
  selector:
    name: brokerflorence
  ports:
  - protocol: TCP
    nodePort: 30310
    targetPort: 30310
    port: 30310
    name: grpc
  - protocol: TCP
    nodePort: 30311
    targetPort: 30311
    port: 30311
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-brokerparis
  labels:
    run: blockchain-brokerparis
spec:
  type: NodePort
  selector:
    name: brokerparis
  ports:
  - protocol: TCP
    nodePort: 30410
    targetPort: 30410
    port: 30410
    name: grpc
  - protocol: TCP
    nodePort: 30411
    targetPort: 30411
    port: 30411
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-insuranceflorence
  labels:
    run: blockchain-insuranceflorence
spec:
  type: NodePort
  selector:
    name: insuranceflorence
  ports:
  - protocol: TCP
    nodePort: 30510
    targetPort: 30510
    port: 30510
    name: grpc
  - protocol: TCP
    nodePort: 30511
    targetPort: 30511
    port: 30511
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-insuranceparis
  labels:
    run: blockchain-insuranceparis
spec:
  type: NodePort
  selector:
    name: insuranceparis
  ports:
  - protocol: TCP
    nodePort: 30610
    targetPort: 30610
    port: 30610
    name: grpc
  - protocol: TCP
    nodePort: 30611
    targetPort: 30611
    port: 30611
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ownerflorence
  labels:
    run: blockchain-ownerflorence
spec:
  type: NodePort
  selector:
    name: ownerflorence
  ports:
  - protocol: TCP
    nodePort: 30710
    targetPort: 30710
    port: 30710
    name: grpc
  - protocol: TCP
    nodePort: 30711
    targetPort: 30711
    port: 30711
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ownerparis
  labels:
    run: blockchain-ownerparis
spec:
  type: NodePort
  selector:
    name: ownerparis
  ports:
  - protocol: TCP
    nodePort: 30810
    targetPort: 30810
    port: 30810
    name: grpc
  - protocol: TCP
    nodePort: 30811
    targetPort: 30811
    port: 30811
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-provenanceflorence
  labels:
    run: blockchain-provenanceflorence
spec:
  type: NodePort
  selector:
    name: provenanceflorence
  ports:
  - protocol: TCP
    nodePort: 30910
    targetPort: 30910
    port: 30910
    name: grpc
  - protocol: TCP
    nodePort: 30911
    targetPort: 30911
    port: 30911
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-provenanceparis
  labels:
    run: blockchain-provenanceparis
spec:
  type: NodePort
  selector:
    name: provenanceparis
  ports:
  - protocol: TCP
    nodePort: 31010
    targetPort: 31010
    port: 31010
    name: grpc
  - protocol: TCP
    nodePort: 31011
    targetPort: 31011
    port: 31011
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-researchflorence
  labels:
    run: blockchain-researchflorence
spec:
  type: NodePort
  selector:
    name: researchflorence
  ports:
  - protocol: TCP
    nodePort: 31110
    targetPort: 31110
    port: 31110
    name: grpc
  - protocol: TCP
    nodePort: 31111
    targetPort: 31111
    port: 31111
    name: events

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-researchparis
  labels:
    run: blockchain-researchparis
spec:
  type: NodePort
  selector:
    name: researchparis
  ports:
  - protocol: TCP
    nodePort: 31210
    targetPort: 31210
    port: 31210
    name: grpc
  - protocol: TCP
    nodePort: 31211
    targetPort: 31211
    port: 31211
    name: events